# AI Coding Agent Workflow
# Autonomously implements code changes from issues
#
# REQUIRED SECRETS:
# - COPILOT_GITHUB_TOKEN: GitHub PAT with Copilot access (used only for Copilot SDK)
#
# KNOWN LIMITATION:
# GITHUB_TOKEN cannot push .github/workflows/ files (GitHub security restriction).
# If the coding agent generates workflow files, they will be posted as a comment
# on the issue for manual addition. To enable automatic workflow file pushes,
# use a PAT with Contents + Workflows write permissions for checkout instead.
#
# SLASH COMMANDS (post as a comment on an issue or PR):
#   /agent fix [instructions]       - Fix review issues on a PR
#   /agent implement [instructions] - Implement an issue
#   /agent update [instructions]    - Update code based on instructions

name: AI Coding Agent

on:
  issues:
    types: [labeled]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to implement'
        required: false
        type: number
      pr_number:
        description: 'PR number to address feedback for'
        required: false
        type: number

concurrency:
  group: ai-coding-${{ github.event.issue.number || github.event.pull_request.number || github.event.inputs.issue_number || github.event.inputs.pr_number }}
  cancel-in-progress: false

jobs:
  code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: write

    # Trigger on:
    # - 'ready-for-agent' label added to issue
    # - changes_requested review on 'agent-coded' PR
    # - /agent command in comment (on issue or PR)
    # - manual workflow_dispatch
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && github.event.label.name == 'ready-for-agent') ||
      (github.event_name == 'pull_request_review' &&
       github.event.review.state == 'changes_requested' &&
       contains(github.event.pull_request.labels.*.name, 'agent-coded')) ||
      (github.event_name == 'issue_comment' &&
       (startsWith(github.event.comment.body, '/agent') ||
        contains(github.event.issue.labels.*.name, 'agent-coded')) &&
       github.actor != 'github-actions[bot]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install GitHub Copilot CLI
        run: |
          npm install -g @githubnext/github-copilot-cli
          echo "Copilot CLI installed"

      - name: AI Coding Agent
        id: code
        uses: brendankowitz/gh-workflow-agents/actions/coding-agent@main
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          copilot-token: ${{ secrets.COPILOT_GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.issue_number || github.event.issue.number || '' }}
          pr-number: ${{ github.event.inputs.pr_number || github.event.pull_request.number || '' }}
          model: 'claude-sonnet-4.5'
          max-iterations: '5'
          dry-run: 'false'

      - name: Output Results
        if: always()
        run: |
          echo "Status: ${{ steps.code.outputs.status }}"
          echo "Branch: ${{ steps.code.outputs.branch-name }}"
          echo "PR: ${{ steps.code.outputs.pr-number }}"
          echo "Summary: ${{ steps.code.outputs.changes-summary }}"

      - name: Trigger Review
        if: steps.code.outputs.pr-number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ai-review.yml',
              ref: repo.default_branch,
              inputs: { pr_number: String(${{ steps.code.outputs.pr-number }}) }
            });
