# AI Code Review Workflow
# Provides AI-powered code review with security focus
#
# SECURITY: Always pin to a specific commit SHA, not a branch or tag.
# Update the SHA using Dependabot or manually after reviewing changes.
#
# REQUIRED SECRETS:
# - COPILOT_GITHUB_TOKEN: GitHub PAT with "Copilot Requests: Read" permission

name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize]

# Prevent duplicate runs
concurrency:
  group: ai-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    # Skip bot PRs to prevent loops
    if: |
      github.actor != 'github-actions[bot]' &&
      !contains(github.event.pull_request.body || '', '/stop') &&
      !contains(github.event.pull_request.body || '', '/override') &&
      !contains(github.event.pull_request.body || '', '/human')

    steps:
      - name: AI Review
        # TODO: Replace with actual commit SHA after first release
        # Example: uses: brendankowitz/gh-workflow-agents/actions/review-agent@a1b2c3d4e5f6...
        uses: brendankowitz/gh-workflow-agents/actions/review-agent@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          copilot-token: ${{ secrets.COPILOT_GITHUB_TOKEN }}
          model: claude-sonnet-4.5
          auto-approve-dependabot: 'true'
          security-focus: 'true'
