# AI Issue Triage with Automatic Assignment
# Classifies issues and automatically assigns actionable ones to Copilot
#
# SECURITY: Always pin to a specific commit SHA, not a branch or tag.
#
# REQUIRED SECRETS:
# - COPILOT_GITHUB_TOKEN: GitHub PAT with "Copilot Requests: Read" permission

name: AI Issue Triage
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: number

concurrency:
  group: ai-triage-${{ github.event.issue.number || github.event.inputs.issue_number }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    # Allow bot-created issues for autonomous pipelines, but skip dependabot.
    # The triage agent has its own bot-actor check that exempts workflow_dispatch
    # and issues events, so it's safe to let bot actors through at the workflow level.
    if: |
      github.event_name == 'workflow_dispatch' || (
        github.actor != 'dependabot[bot]' &&
        !contains(github.event.comment.body || '', '/stop') &&
        !contains(github.event.comment.body || '', '/human')
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install GitHub Copilot CLI
        run: |
          npm install -g @github/copilot
          echo "GitHub Copilot CLI installed at: $(which copilot || echo 'not in path')"
          copilot --version || echo "CLI installed"

      - name: AI Triage
        id: triage
        uses: brendankowitz/gh-workflow-agents/actions/triage-agent@main
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          copilot-token: ${{ secrets.COPILOT_GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.issue_number || '' }}
          model: claude-sonnet-4.5
          enable-duplicate-detection: 'true'
          enable-auto-label: 'true'

      - name: Log Decision
        run: |
          echo "Classification: ${{ steps.triage.outputs.classification }}"
          echo "Actionable: ${{ steps.triage.outputs.is-actionable }}"
          echo "Vision Aligned: ${{ steps.triage.outputs.aligns-with-vision }}"
          echo "Recommended Action: ${{ steps.triage.outputs.recommended-action }}"
